title : Практикум по компьютерным технологиям
author: Fadeev Egor
logo: 'logo.png'

# Short description about the book
description: >-
  Курс лекций по дисциплине "Практикум по компьютерным технологиям".

execute:
  execute_notebooks: 'off'
  allow_errors     : true
  
# HTML-specific settings
html:
  favicon                     : "favicon.png" 
  home_page_in_navbar         : true
  use_repository_button       : true
  use_issues_button           : true
  use_edit_page_button        : true

# Interact link settings
notebook_interface            : "notebook"

only_build_toc_files: true

sphinx:
  config:
    html_extra_path: ['assets']
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    
# Launch button settings
repository:
  url: https://github.com/FadeevLecturer/python_lectures
  branch: main 
launch_buttons:
  colab_url: "https://colab.research.google.com"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib

